name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.0.1

  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme CocoaHeadsNL -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4' | xcpretty && exit ${PIPESTATUS[0]}
      
  Archive:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive artifact
      run: xcodebuild clean archive -archivePath $PWD/build/CocoaHeadsNL.xcarchive -scheme CocoaHeadsNL -project CocoaHeadsNL/CocoaHeadsNL.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1' | xcpretty && exit ${PIPESTATUS[0]}
    - uses: actions/upload-artifact@v2
      with:
        name: artifact-CocoaHeadsNL.app
        path: $PWD/build/CocoaHeadsNL.xcarchive/CocoaHeadsNL.app

